server:
  port: ${PORT:8080}
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        secure: true
        same-site: lax
spring:
  ai:
    vertex:
      ai:
        gemini:
          api-key: ${GEMINI_API_KEY}
          project-id: dummy-project-id
          location: us-central1
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

app:
  security:
    username: ${APP_USERNAME}
    password: ${APP_PASSWORD}
